var markets = 
 [
 ["1005876",
 "Farmers Market",
 "http://Farmersmarket.com",
 "5960 Main Road",
 "City Junction",
 "Madurai",
 "Madurai",
 "625001",
 "78.1198",
 "9.9252",
 "Faith-based institution (e.g., church, mosque, synagogue, temple)",
 "Y","N","N","N","N","Y","Y","N","Y","N","Y","Y","Y","Y","Y","N","Y","N","Y","Y","Y"],
 ["1005876",
 "Flower Bazaar",
 "http://Flowerbazaar.com",
 "5960 Stewart Parkway",
 "Mylapore",
 "Chennai",
 "Chennai",
 "600001",
 "80.2707",
 "13.0826",
 "Faith-based institution (e.g., church, mosque, synagogue, temple)",
 "Y","N","N","N","N","Y","Y","N","Y","N","Y","Y","Y","Y","Y","N","Y","N","Y","Y","Y"]];